[Interface]
Address = 192.168.6.122/32
DNS = 1.1.1.1,8.8.8.8
PrivateKey = 4KDNcTLd7MbWZRV//wgIa7AI+TfNv+MYfgUjHeh/QlM=

[Peer]
PublicKey=LZg89RAqejsZi6rhPIiSalWqDojKt08km4WIIlYh0zI=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = ca2.vpnjantit.com:1024
