[Interface]
Address = 192.168.6.41/32
DNS = 1.1.1.1,8.8.8.8
PrivateKey = 4KOeiijIU63tT3abRgvrVwM3MrpY51SWhv1sksxhbkI=

[Peer]
PublicKey=n+SMIu7n+s8ARaAFVo7o3li5LGjeG14yNjKPyK9S7hc=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = ru2.vpnjantit.com:1024
