[Interface]
Address = 192.168.6.248/32
DNS = 1.1.1.1,8.8.8.8
PrivateKey = kMdUd9Ze1KudfObQKG9XSnaf5o3ptnfsJIdTJyAioWw=

[Peer]
PublicKey=wkgxhVoGxrOxBmVLaMcZ4q0Xs4pVZdYl6CyQEBg0gQI=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = ca3.vpnjantit.com:1024
