[Interface]
Address = 192.168.6.23/32
DNS = 1.1.1.1,8.8.8.8
PrivateKey = mDNkfrt7a1hPp0PNyOZnv5Ty97MWXymK4FXLC9PXXUM=

[Peer]
PublicKey=EsPO+q2MH03MPNp7Hu0qJ58UzKEOKiS5w4IhdXg9gRg=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = cl1.vpnjantit.com:1024
